### ISSUE TITLE
`<internal>.default` replacement stopped working after upgrading from 0.4.0 to 0.6.1

### ISSUE THREAD

**Issue by fionnachan** [felipecrs/typedoc-plugin-rename-defaults#5]
The name of `<internal>.default` classes discovered using the https://github.com/Gerrit0/typedoc-plugin-missing-exports plugin used to be replaced correctly at 0.4.0 but after upgrading to 0.6.1, `<internal>.default` would be replaced by `<internal>.<internal>`

I am confident the behaviour is due to this plugin because when the documentation was produced without this plugin, the results from the previous version of typedoc & typedoc-plugin-missing-exports are same as the latest version.

0.4.0:
https://algorand.github.io/js-algorand-sdk/classes/Algodv2.html#accountApplicationInformation

0.6.1:
https://upgrade-typedoc-and-plugins--js-algosdk.netlify.app/classes/algodv2#accountApplicationInformation

Version changes:
https://github.com/fionnachan/js-algorand-sdk/commit/205d878cbda84edcc7d8b488f5d39c68fdcf8d31

**Comment by felipecrs** [comment]
Checking...

**Comment by felipecrs** [comment]
https://github.com/felipecrs/typedoc-plugin-rename-defaults/commit/efe343749006d11018f1d5b683b5716febc9ca25 should fix this issue. Thanks for reporting it.

v0.6.2 was released and contain the fix, I would appreciate your feedback on it.

**Comment by fionnachan** [comment]
Thanks for the quick response but unfortunately it is still not working :(

This is the tsdoc config:
https://github.com/fionnachan/js-algorand-sdk/blob/0bd8306a0aacb416cbc4c093cd99c952cb39919d/typedoc.config.json#L1-L6


This is one of the snippets:
https://github.com/fionnachan/js-algorand-sdk/blob/0bd8306a0aacb416cbc4c093cd99c952cb39919d/src/client/v2/algod/algod.ts#L180-L187

**Comment by felipecrs** [comment]
Got it. Thanks again for replying back.

TypeDoc 0.23.0 removed a parameter which I used to rely on. On my tests, I found an alternative, but this alternative does not seem to work in your test (which is good we caught).

The issue which I fixed in 0.6.2 turned out to be something else even, which was also a valid bug.

I'm yet looking for an alternative to `node.name` therefore, here is where I refactored it: https://github.com/felipecrs/typedoc-plugin-rename-defaults/commit/0a24014e7784c83ca103eb42461079c7a7a17c15

**Comment by fionnachan** [comment]
Thanks Felipe. I'm not familiar with the TypeDoc mechanics so don't know how to help :(

In any case, my upgrade is not urgent so I'll just hold it off until there's more clarity on the fix for this bug.

**Comment by felipecrs** [comment]
@Gerrit0, for some reason, in @fionnachan's project, the `reflection.escapedName` does not get filled with the original (non `default`) name. For every other situation, it seems to have the original name.

Look at these pictures:

0.22:

![image](https://user-images.githubusercontent.com/29582865/177648391-dd19637a-d405-406f-a8c6-fe4b86a503cf.png)

0.23:

![image](https://user-images.githubusercontent.com/29582865/177648188-6a4d81f2-a74b-4a47-99a9-802834fe790d.png)

I wonder if this is a bug in TypeDoc. But if it's not, I have not found an alternative for `node.name.getText()` since it got removed at https://github.com/TypeStrong/typedoc/commit/44bf2eca25e396ab2fad17bb11e664afbeb0ca2d.

**Comment by felipecrs** [comment]
I think I was able to nail down the issue. The following:

```js
export default function test6Function(param: string) {
  return;
}
```

Generates a `reflection.escapedName` of `default` rather than `test6Function`.

**Comment by felipecrs** [comment]
Alright, I found a way to bypass it. I think it's a little hacky though.

```js
context.project.getSymbolFromReflection(reflection).valueDeclaration.name.getText()
```

Version 0.6.3 contains the [fix](https://github.com/felipecrs/typedoc-plugin-rename-defaults/commit/04307b8c75135ba2b3d34148b95b83d18db516b1).

**Comment by Gerrit0** [comment]
This is working as intended as far as TypeDoc is concerned. `escapedName` exists only to resolve names within a class/interface for comment inheritance, so your use of the property isn't considered supported.

Your fix doesn't cover:

```ts
export default interface A {
    x: string;
}
```

Because `valueDeclaration` will only be set on symbols which create a value. You probably want to grab `symbol.declarations` and grab the name from the first on there.

Yes, this is kind of hacky, but really the only thing that changed is that this hackery used to be kind of hidden from you because TypeDoc arbitrarily chose a declaration when giving a node to event listeners.

**Comment by felipecrs** [comment]
Thanks a lot, @Gerrit0! I integrated your suggestion in v0.6.4.

Thanks for the rationale btw.

**Comment by fionnachan** [comment]
@felipecrs @Gerrit0 thank you both!

Does each of you have an Algorand address?
If not, you can create one on a wallet. I'll send you some Algos to try out ❤

https://perawallet.app/

Evidence that it's a trustworthy wallet:
https://www.algorand.com/resources/algorand-announcements/introducing-the-newly-designed-algorand-wallet
https://blog.perawallet.app/its-official-algorand-wallet-is-now-pera-wallet-171561597664
